# Generated by Django 3.1.4 on 2020-12-11 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20201211_2009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinstance',
            old_name='borrower',
            new_name='borrowed',
        ),
    ]
