# Generated by Django 3.1.4 on 2020-12-17 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20201211_2033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinstance',
            old_name='borrowed',
            new_name='borrower',
        ),
    ]
